### ISSUE TITLE
Package name suggestion

### ISSUE THREAD

**Issue by kerelape** [objectionary/eo-threads#2]
In my opinion, this would be more convinient to call the base package `QQ.concurrent` (or `QQ.concurrency`) rather than `QQ.threads`.

**Comment by levBagryansky** [comment]
@yegor256 what do you think considering that there could be `mutex`s and anything else?

**Comment by yegor256** [comment]
@kerelape @levBagryansky maybe `QQ.pp` (parallel processing)? or `QQ.mx` (multiplexing)?

**Comment by levBagryansky** [comment]
@yegor256 in my opinion the "concurrency" is clearer, but the "multiplexing" sounds cooler

**Comment by yegor256** [comment]
@levBagryansky yes, I would also go with `mx`

**Comment by levBagryansky** [comment]
@yegor256 ok I can rename it in next pull request.

**Comment by levBagryansky** [comment]
@yegor256 do we need renamy repository?

**Comment by yegor256** [comment]
@levBagryansky I think "multiplexing" is not a perfect name for us https://en.wikipedia.org/wiki/Multiplexing Let's stay with `QQ.threads` for now.
