### ISSUE TITLE
Stress test was failed

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-threads#61]
@yegor256 `stress-test` in #59 failed. I think it is better to disable the test and create more tests in java which would simulate the eo code.

**Comment by levBagryansky** [comment]
This test can be the cause:
https://github.com/objectionary/eo/issues/1299

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#67](https://github.com/objectionary/eo-threads/issues/67) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the only puzzle [#67](https://github.com/objectionary/eo-threads/issues/67) is solved here.
