### ISSUE TITLE
codecov is not configured

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-threads#70]
See how it's done in eo-files or eo-collections. We should do the same here, with a badge

**Comment by levBagryansky** [comment]
@yegor256 `codecov.yml` here is identical to `codecov.yml` in `eo-collections` and `eo-files`. Apparently the badge in pr #73 displays "not found" because the repository is "not yet setup" [here](https://app.codecov.io/gh/objectionary/+). In `eo-collections` the badge is "not found" too.

**Comment by levBagryansky** [comment]
@yegor256 codecov badge is already working now. Can we close the issue?

**Comment by yegor256** [comment]
@levBagryansky yes
