### ISSUE TITLE
first release

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-threads#72]
Let's configure Rultor the same way it's done in eo-files, and release the first version to Maven Central

**Comment by levBagryansky** [comment]
@yegor256 configuration files `.rultor.yml` here and in `eo-files` are already the same. I don't seem to be able to set up Rultor anymore.

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.2`

**Comment by yegor256** [comment]
@levBagryansky done
